apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"          # explicit opt-in (optional, but fine)
        mesh.redeploy.ts: "2025-11-06T23:45:00Z"
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: jaiganeshinfotech/hello:latest
        ports:
        - containerPort: 3000
        env:
        - name: LOG_NOISE
          value: "true"
        - name: LOG_INTERVAL_MS
          value: "2000"
        - name: PORT
          value: "3000"
        # JSON logs go to stdout â€” Datadog will ingest automatically