apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello
  labels: { app: hello-world, version: v1 }
spec:
  replicas: 1
  selector:
    matchLabels: { app: hello-world, version: v1 }
  template:
    metadata:
      labels: { app: hello-world, version: v1 }
      annotations:
        sidecar.istio.io/inject: "true"          # explicit opt-in (optional, but fine)
        mesh.redeploy.ts: "2025-11-06T23:45:00Z"
    spec:
      containers:
      - name: hello-world
        image: jaiganeshinfotech/hello:latest
        ports: [{ containerPort: 3000 }]
        env:
        - name: LOG_NOISE
          value: "true"
        - name: LOG_INTERVAL_MS
          value: "2000"
        - name: PORT
          value: "3000"