apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-v2
  namespace: hello
  labels: { app: hello-world, version: v2 }
spec:
  replicas: 1
  selector:
    matchLabels: { app: hello-world, version: v2 }
  template:
    metadata:
      labels: { app: hello-world, version: v2 }
    spec:
      containers:
      - name: hello-world
        image: hashicorp/http-echo:0.2.3
        args: ["-text=Hello from v2", "-listen=:3000"]
        ports: [{ containerPort: 3000 }]